#!/usr/bin/env bash
#
# ------------------------------------------------------------------------------
# This script collects all data generated by the experimental scripts and stores
# it in a single zip file.
#
# Usage:
# get-data.sh
#   --experiments_data_dir <path, directories (use seperator ',' for more than one) with data generated by experimental scripts>
#   --output_file <path, file to which data will be written>
#   [help]
#
# Requirements:
#   Execution of ../tools/get-tools.sh script.
# ------------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
source "$SCRIPT_DIR/../utils/experiments/utils.sh" || exit 1

# ------------------------------------------------------------------------- Deps

# Check whether 'Rscript' is available
Rscript --version > /dev/null 2>&1 || die "[ERROR] Could not find 'Rscript' required to collect all data in a single CSV file. Please install 'R' and re-run the script."

# ------------------------------------------------------------------------- Args

USAGE="Usage: ${BASH_SOURCE[0]} --experiments_data_dir <path, directories (use seperator ',' for more than one) with data generated by experimental scripts> --output_file <path, file to which data will be written> [help]"
if [ "$#" -ne "1" ] && [ "$#" -ne "4" ]; then
  die "$USAGE"
fi

EXPERIMENTS_DATA_DIR=""
OUTPUT_FILE=""

while [[ "$1" = --* ]]; do
  OPTION=$1; shift
  case $OPTION in
    (--experiments_data_dir)
      EXPERIMENTS_DATA_DIR=$1;
      shift;;
    (--output_file)
      OUTPUT_FILE=$1;
      shift;;
    (--help)
      echo "$USAGE"
      exit 0
    (*)
      die "$USAGE";;
  esac
done

[ "$EXPERIMENTS_DATA_DIR" != "" ] || die "[ERROR] Missing --experiments_data_dir argument!"
[ "$OUTPUT_FILE" != "" ]          || die "[ERROR] Missing --output_file argument!"

for exps_dir in $(echo "$EXPERIMENTS_DATA_DIR" | tr ',' '\n'); do
  [ -d "$exps_dir" ] || die "[ERROR] $exps_dir does not exist!"
done

rm -f "$OUTPUT_FILE"
touch "$OUTPUT_FILE" || die "[ERROR] Failed to create '$OUTPUT_FILE'!"

# ------------------------------------------------------------------------- Main

Rscript "$SCRIPT_DIR/get-data.R" "$EXPERIMENTS_DATA_DIR" "$OUTPUT_FILE" || die "[ERROR] Failed to run '$SCRIPT_DIR/get_data.R'!"

echo "DONE!"
exit 0

# EOF
