#!/usr/bin/env bash
#
# ------------------------------------------------------------------------------
# This script collects all data generated by the experimental scripts and stores
# it in a single zip file.
#
# Usage:
# get-data.sh
#   --experiments_data_dir <path, directories (use seperator ',' for more than one) with data generated by experimental scripts>
#   --output_file <path, file to which data will be written, e.g., generated/data.csv.gz>
#   [help]
#
# Requirements:
#   Execution of ../../tools/get-tools.sh script.
# ------------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"

#
# Print error message to the stdout and exit.
#
die() {
  echo "$@" >&2
  exit 1
}

# ------------------------------------------------------------------------- Deps

# Check whether 'Rscript' is available
Rscript --version > /dev/null 2>&1 || die "[ERROR] Could not find 'Rscript' required to collect all data in a single CSV file. Please install 'R' and re-run the script."

# ------------------------------------------------------------------------- Args

USAGE="Usage: ${BASH_SOURCE[0]} \
  --experiments_data_dir <path, directories (use seperator ',' for more than one) with data generated by experimental scripts> \
  --output_file <path, file to which data will be written, e.g., generated/data.csv.gz> \
  [help]"
if [ "$#" -ne "1" ] && [ "$#" -ne "4" ]; then
  die "$USAGE"
fi

experiments_data_dir=""
output_file=""

while [[ "$1" = --* ]]; do
  OPTION=$1; shift
  case $OPTION in
    (--experiments_data_dir)
      experiments_data_dir=$1;
      shift;;
    (--output_file)
      output_file=$1;
      shift;;
    (--help)
      echo "$USAGE"
      exit 0
    (*)
      die "$USAGE";;
  esac
done

[ "$experiments_data_dir" != "" ] || die "[ERROR] Missing --experiments_data_dir argument!"
[ "$output_file" != "" ]          || die "[ERROR] Missing --output_file argument!"

for experiment_data_dir in $(echo "$experiments_data_dir" | tr ',' '\n'); do
  [ -d "$experiment_data_dir" ] || die "[ERROR] $experiment_data_dir does not exist!"
done

rm -f "$output_file"
touch "$output_file" || die "[ERROR] Failed to create '$output_file'!"

# ------------------------------------------------------------------------- Main

Rscript "$SCRIPT_DIR/get-data.R" "$experiments_data_dir" "$output_file" || die "[ERROR] Failed to run '$SCRIPT_DIR/get_data.R'!"

echo "DONE!"
exit 0

# EOF
